user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
user_adminpage:
    path:     /admin
    defaults: { _controller: UserBundle:Default:admin }
user_userpage:
    path:     /user
    defaults: { _controller: UserBundle:Default:user }
